apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: caph-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: caph-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: caph-controller-manager
      annotations:
        kubectl.kubernetes.io/default-logs-container: manager
    spec:
      containers:
        - command:
            - /manager
          args:
            - "--leader-elect=true"
            - "--diagnostics-address=${CAPH_DIAGNOSTICS_ADDRESS:=:8443}"
            - "--insecure-diagnostics=${CAPH_INSECURE_DIAGNOSTICS:=false}"
          image: controller:latest
          name: manager
          ports:
            - containerPort: 9440
              name: healthz
              protocol: TCP
            - containerPort: 8443
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 150m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 100Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
